package main

var extensionIcons = map[string]string{
	"go":   "",
	"md":   "",
	"json": "",
	"js":   "",
	"ts":   "",
	"py":   "",
	"rb":   "",
	"java": "",
	"c":    "",
	"cpp":  "",
	"h":    "",
	"hpp":  "",
	"rs":   "",
	"html": "",
	"css":  "",
	"scss": "",
	"php":  "",
	"sh":   "",
	"bash": "",
	"zsh":  "",
	"fish": "",
	"yml":  "",
	"yaml": "",
	"toml": "",
	"xml":  "",
	"ini":  "",
	"conf": "",
	"cfg":  "",
	"dockerfile": "",
	"zip":  "",
	"tar":  "",
	"gz":   "",
	"7z":   "",
	"rar":  "",
	"png":  "",
	"jpg":  "",
	"jpeg": "",
	"gif":  "",
	"svg":  "",
	"mp3":  "",
	"wav":  "",
	"mp4":  "",
	"mkv":  "",
	"mov":  "",
	"pdf":  "",
	"txt":  "",
	"lock": "",
	"gitignore": "",
}

var extensionColors = map[string]string{
	"go":   Cyan,
	"js":   Yellow,
	"ts":   Blue,
	"py":   Yellow,
	"rb":   Red,
	"java": Red,
	"c":    Blue,
	"cpp":  Blue,
	"rs":   Red,
	"html": Red,
	"css":  Blue,
	"scss": Purple,
	"php":  Purple,
	"sh":   Green,
	"bash": Green,
	"zsh":  Green,
	"yml":  Purple,
	"yaml": Purple,
	"json": Yellow,
	"md":   Yellow,
	"zip":  Red,
	"tar":  Red,
	"gz":   Red,
	"png":  Purple,
	"jpg":  Purple,
	"jpeg": Purple,
	"gif":  Purple,
	"svg":  Purple,
	"mp3":  Cyan,
	"mp4":  Cyan,
	"pdf":  Red,
}

var specialFileIcons = map[string]string{
	"Makefile": "",
	"LICENSE":  "⚖️",
	"README.md": "",
}
